sudo: false

os:
  - osx
  - linux

language: dart
dart:
  - stable

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - nvm install 6
  - dart --version
  - node --version
  - npm --version

install:
  - npm install --depth 0

script:
  - npm run vscode:prepublish
  - npm test
