sudo: false

os:
  - osx
  - linux

language: node_js
node_js: lts/*
  
addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      export DART_OS=macos;
    else
      export DART_OS=linux;
    fi
  - curl https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-$DART_OS-x64-release.zip > dart-sdk.zip
  - curl https://storage.googleapis.com/dart-archive/channels/dev/release/latest/sdk/dartsdk-$DART_OS-x64-release.zip > dart-sdk-dev.zip
  - unzip dart-sdk.zip > /dev/null
  - unzip dart-sdk-dev.zip -d dev > /dev/null
  - git clone -b beta https://github.com/flutter/flutter.git
  - cd flutter
  - git worktree add ../dev/flutter origin/master
  - cd ..
  - export PATH=`pwd`/dart-sdk/bin:`pwd`/flutter/bin:$PATH
  - flutter config --no-analytics
  - dart --version
  - flutter --version
  - dev/dart-sdk/bin/dart --version
  - dev/flutter/bin/flutter --version
  - node --version
  - npm --version

install:
  - npm install --depth 0

script:
  - npm run vscode:prepublish
  - npm run lint
  - npm test
