install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version.$env:APPVEYOR_BUILD_NUMBER"
  - ps: Install-Product node ''
  - ps: Invoke-WebRequest "https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-windows-x64-release.zip" -OutFile "dart.zip"
  - ps: Invoke-WebRequest "https://storage.googleapis.com/dart-archive/channels/dev/release/latest/sdk/dartsdk-windows-x64-release.zip" -OutFile "dart-dev.zip"
  - ps: 7z.exe x dart.zip | out-null
  - ps: 7z.exe x -odev dart-dev.zip | out-null
  - git clone -b beta https://github.com/flutter/flutter.git
  - pushd flutter
  - git worktree add ..\dev\flutter origin\master
  - popd
  - ps: $env:PATH = "$pwd\dart-sdk\bin;$pwd\flutter\bin;" + $env:PATH
  - ps: $env:PATH_UNSTABLE = "$pwd\dev\dart-sdk\bin;$pwd\dev\flutter\bin"
  - flutter config --no-analytics
  - ps: $env:ELECTRON_NO_ATTACH_CONSOLE = 1
  - dart --version
  - flutter --version
  - dev\dart-sdk\bin\dart --version
  - dev\flutter\bin\flutter --version
  - node --version
  - npm --version

build_script:
  - npm install --depth 0 --silent
  - npm run vscode:prepublish --silent
  - npm run lint --silent

test_script:
- npm test
