blank_issues_enabled: true
contact_links:
  - name: Flutter SDK Issues
    url: https://github.com/flutter/flutter/issues/new
    about: Issues relating to Flutter that can be reproduced in IntelliJ/Android Studio or the command line should be reported in the Flutter SDK repository
  - name: Dart SDK Issues
    url: https://github.com/dart-lang/sdk/issues/new
    about: Issues relating to editing Dart code that also occur in IntelliJ/Android Studio should be reported in the Dart SDK repository
