name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "37 15 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked stale because it is tagged awaiting-info for 30 days with no activity. Remove the stale label or comment to prevent the issue being closed in 10 days.'
        stale-issue-label: 'stale'
        only-labels: 'awaiting-info'
        days-before-stale: 30
        days-before-close: 10
